### ISSUE TITLE
你好，请问你的程序能下载小说封面图片吗？

### ISSUE THREAD

**Issue by mk2016a** [Dothion/esjspy#2]
我写的程序扒这个网站的小说，下载封面图片是失败的。
请问有没有什么有效保存网页图片的方法。
感谢回复。

**Comment by mk2016a** [comment]
你的程序真规范，写的太棒了，特别是debug。

**Comment by Dothion** [comment]
很可能是没有挂梯子，挂梯子然后设置本地http代理为127.0.0.1:12333

**Comment by mk2016a** [comment]
这里图片是能够正常显示的。但我想用程序下载的时候就403 Forbidden了。
请教遇到这种情况，如何正确的下载图片儿呢？
